# -*- coding: utf-8 -*-
"""numpy.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1tsUItA1pBr8SszmT7yc7Ql7JthNlGB7e
"""

import numpy as np

#creating arrays
a=np.array([1,2,3])
print("Array a:",a)
b=np.array([[1,2,3],[4,5,6]])
print("Array b:\n",b)

#array indexing and slicing
print("First element of a: ",a[0])
print("First row of b:",b[0, :])

#Array operations
c =a + 10
print("Array c: ",c)
d=b*2
print("Array d: \n",d)

#Broadcasting
e=a*np.array([1,2,3])
print("Array e: ",e)

#Advanced indexing
f=b[[0,1],[1,2]]
print(" Advanced indexing: ",f)

#Linear Algebra operations
g=np.dot(a,a)
print("Dot prodct g: ",e)